/// Canonical system-drawn traces shown after virtual hardware actions.
enum SystemTraceId {
  modeMessageReceive,
  modeBottleMail,
  modeSpecificUserSend,
  notificationsOn,
  notificationsOff,
  autoPlayOn,
  autoPlayOff,
  messagePlayback,
  randomMessage,
  replayMessage,
  friendConnected,
  friendUnavailable,
  destinationSelected,
  nameTraceRegistrationPrompt,
  nameTraceSaved,
  nameTraceSaveFailed,
  senderRemoved,
  autoContinuousOn,
  autoContinuousOff,
  settingsPortal,
  alert,
  bottleDiscarded,
  bottleSent,
  bottleError,
  noMessageFound,
}
